version: '3.8'

services:
  ssl-cert-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssl-certificate-generator
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      # 邮件服务器配置
      - MAIL_SERVER=${MAIL_SERVER:-smtp.163.com}
      - MAIL_PORT=${MAIL_PORT:-465}
      - MAIL_USE_SSL=${MAIL_USE_SSL:-true}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      # Flask应用密钥
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
    volumes:
      - ./ssl_certificates.db:/app/ssl_certificates.db
    networks:
      - ssl-cert-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ssl-cert-network:
    driver: bridge

